### ISSUE TITLE
Automatically include from keywords.txt of libraries

### ISSUE THREAD

**Issue by z3t0** [sudar/vim-arduino-syntax#4]
Any ideas on how we can make this work?

**Comment by sudar** [comment]
I don't have any definite idea on this.

One thing that we can do is to ask the user to specify their library folder in their `vimrc` and then we can go over all the sub directories and then pick up the keywords.txt file, parse it, get the keywords and then dynamically insert them into syntax.

**Comment by z3t0** [comment]
As long as we can run python scripts this should work I'm almost done with a script that does exactly this.

**Comment by z3t0** [comment]
Fixed in pull request #7 
https://github.com/sudar/vim-arduino-syntax/pull/7
